[build]
publish = "public"
command = "git submodule update --init --recursive && hugo"

[context.production.environment]
HUGO_VERSION = "0.140.2"  # Use your Hugo version
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"